% Build mex
mex LDFLAGS='-larmadillo'...
HigherOrderMS1D_wrapper.cpp ArmadilloConverter.cpp CalcGivensAngles.cpp...
Compute1rErrors.cpp FindBestPartition.cpp ReconstructionFromPartition.cpp...
Interval.cpp
